### ISSUE TITLE
Explain how to edit primary documentation

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/docs#34]
Here is a web page rendering documentation:

https://docs.aion.network/docs/migrating-smart-contracts-from-ethereum

It would be nice if there is a link on that page to directly submit a PR to improve content on that page.

It seems like this repository does *not* generate the https://docs.aion.network/ website. If I cannot find the repository that generates documentation I'm reading on a web page then by default I assume the documentation is manually compiled/deployed and is outdated.

**Comment by johnnymatthews** [comment]
> It seems like this repository does not generate the https://docs.aion.network/ website.

You're correct. The docs.aion.network needs to be manually updated whenever there are changes. Obviously this is super annoying, and takes up quite a bit of time.

The service Aion uses to host it's documentation does not have a system in place to link directly to a Github repo. Because of this, we're moving away from the platform, and are building a new docs site based on the [Hugo Static Site](https://gohugo.io/) generator. We'll be putting out a post that explains why we're doing this in more detail (I'll link it here once it's out).

As it stands right now, any changes made do this repo are manually copied over to the Readme.io platform at the end of the week. If you notice any inconsistencies, please raise them as issues on this repo. Treat this repo as the source-of-truth.
