### ISSUE TITLE
Documentation cites old Ubuntu LTS version

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/docs#35]
On page https://docs.aion.network/docs/smart-contract-demo-dapp it states:

> Currently the compiler binary is built for 64-bit Ubuntu 16.04, other versions of Ubuntu may not be fully compatible.

At this time, the Ubuntu 16.04 release only has maintenance updates (per https://www.ubuntu.com/about/release-cycle). Please update instructions for the latest LTS version which is 18.04.

**Comment by johnnymatthews** [comment]
Thanks for raising this @fulldecent.

This guide uses the Aion FastVM instead of the new Aion Virtual Machine (AVM). When this guide was written, the FastVM was built for Ubuntu 16.04. The recommended Ubuntu version for the FastVM is still 16.04.

The age of this guide, and Aion's preference to use the AVM makes me not want to change the guide. However, a notice explaining this comment is probably a good idea.
